spring.datasource.url=jdbc:postgresql://localhost:5432/necesidades_db
spring.datasource.username=postgres
spring.datasource.password=Lukas.2424

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

resilience4j.circuitbreaker.instances.osm.failureRateThreshold=50
resilience4j.circuitbreaker.instances.osm.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.osm.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.osm.slidingWindowSize=5